### ISSUE TITLE
rename this tool from "rqt_console" to "rqt_log" / something else

### ISSUE THREAD

**Issue by felixf4xu** [ros-visualization/rqt_console#43]
rqt_console is basically a tool to view ros logs (in the UI, it's called "message" at the column header).

the current name of `rqt_console` is very mis-leading especially for Windows users, "console" is commonly used for other tools (cmd terminal), it's more like a word which every user has already gotten used to.

btw, I don't suggest to call this tool as "rqt_message", since the word of "message" is more related to node/topic msgs in ros world.

**Comment by 130s** [comment]
I feel you.

`rqt_console` is a graphical frontend of CLI tool, `rosconsole` (in ROS1). A bit of the background of naming  can be seen in http://wiki.ros.org/rosconsole/Package_proposal

Although this name has never been intuitive to me, it's a core tool that has existed for a decade so renaming would probably cause a lot of backlash, which I'm not sure is worthwhile. Also the CLI `rosconsole` is likely discontinued in ROS2 (ref. [discourse.ros.org#6380](https://discourse.ros.org/t/rosconsole-for-ros2/6380/5)). I'm not a maintainer so these are just my thoughts.

**Comment by clalancette** [comment]
> Although this name has never been intuitive to me, it's a core tool that has existed for a decade so renaming would probably cause a lot of backlash, which I'm not sure is worthwhile

Yes, exactly.  I agree that the current name doesn't exactly reflect what it does, but a change here would just cause a lot of user confusion for not a lot of gain.

With that said, I'm going to close this out.  But feel free to keep commenting.
